### ISSUE TITLE
Any library for making forms?

### ISSUE THREAD

**Issue by mdgaziur** [NerdTree-Org/nerdtree#3]
Is there any good library for making forms with Svelte?
We need a good alternative to form libraries in React for Svelte

**Comment by NirobNabil** [comment]
Have you tried svelte-forms-lib? Formik on react was pretty darn good, as this lib immitates formik and also supports yup by default, this looks like a pretty good candidate

**Comment by mdgaziur** [comment]
cool, gonna try it. thanks for the suggestion

**Comment by mdgaziur** [comment]
cool, gonna try it. thanks for the suggestion
